# Introduction to Numpy
#### Author: Dr Abdulkarim M. Jamal Kanaan Jebna
<hr>

Numpy stands for Numerical Python. It provides numerical computation such as max, min, abs, log, ....

In [2]:
# import numpy package
import numpy as np

In [101]:
# returns the maximum value
np.max([1, 3, 5, 0])

5

<code>ndarray</code> is the data structure numpy utilizes. ndarray is a multi-dimensional array. Numpy contains functions to manipulate items of ndarray

In [102]:
# creates one dimension array
array = np.array(range(1, 6))  
array

array([1, 2, 3, 4, 5])

In [103]:
# returns the number of dimensions of an array
array.ndim

1

In [104]:
# returns the shape of the array
array.shape

(5,)

In [105]:
# returns the number of elements of the array
array.size

5

In [106]:
# returns the data type of the array
array.dtype

dtype('int32')

In [107]:
# creates two dimension array; matrix
matrix = np.array([[1,2], [3,4], [5, 6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
# returns the number of dimensions of the matrix
matrix.ndim

2

In [109]:
# returns the shape of the matrix
matrix.shape

(3, 2)

In [110]:
# returns the data type of the array
matrix.dtype

dtype('int32')

In [111]:
# creates an ndarray of two rows and three columns
x = np.ndarray([2,3])
x

array([[-0.25737728, -1.75016021, -1.5605778 ],
       [-0.29633394, -0.10188751,  0.27691761]])

In [112]:
# assigns a value to a specific cell
x[0, 0] = 10
x

array([[10.        , -1.75016021, -1.5605778 ],
       [-0.29633394, -0.10188751,  0.27691761]])

In [113]:
# selects an element
x[0, 0]

10.0

<hr>

#### use a list to select elements

In [135]:
selector = [[0, 1, 1], [0, 1, 2]] # element-wise
selector

[[0, 1, 1], [0, 1, 2]]

In [134]:
x[tuple(selector)]

array([10.        , -0.10188751,  0.27691761])

In [137]:
x[tuple(selector)] = -10
x

array([[-10.        ,  -1.75016021,  -1.5605778 ],
       [ -0.29633394, -10.        , -10.        ]])

<hr>

### built-in functions

##### <code>rand</code> function returns random values in uniform distribution between [0,1] in a given shape. 

In [36]:
# returns random values in a given shape
# array
np.random.rand(5)

array([0.34274728, 0.49399387, 0.06149162, 0.41391787, 0.04478911])

In [38]:
# matrix
np.random.rand(5, 2)

array([[0.02044178, 0.54961412],
       [0.68339947, 0.21952062],
       [0.11990797, 0.28605608],
       [0.79806222, 0.91003837],
       [0.76546423, 0.16004812]])

In [39]:
# creates an array from a normal distribution
np.random.randn(5)

array([-0.78293306, -0.92108768, -0.76004764,  0.13748944,  0.45134641])

In [40]:
# creates ndarray; its functionality is similar to range function. 
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [50]:
# returns an array containing the same data but in a new shape 
x = np.arange(10)
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
# returns evenly spaced numbers over a specified interval.
np.linspace(start=0, stop=10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [61]:
# returns numbers spaced evenly on a log scale from 10^-2 to 10^+2
np.logspace(start=-2, stop=2, num=20)

array([1.00000000e-02, 1.62377674e-02, 2.63665090e-02, 4.28133240e-02,
       6.95192796e-02, 1.12883789e-01, 1.83298071e-01, 2.97635144e-01,
       4.83293024e-01, 7.84759970e-01, 1.27427499e+00, 2.06913808e+00,
       3.35981829e+00, 5.45559478e+00, 8.85866790e+00, 1.43844989e+01,
       2.33572147e+01, 3.79269019e+01, 6.15848211e+01, 1.00000000e+02])

In [62]:
# returns a new array of given shape and type, filled with zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# returns a new array of given shape and type, filled with ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
# returns a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
# performing slicing
x = np.arange(-10, 10, 2)
x

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [76]:
# slicing
x[1:3]

array([-8, -6])

In [77]:
# ndarray provides support to the indexing
x = np.arange(-10, 10, 2)
x[x < 0]

array([-10,  -8,  -6,  -4,  -2])

In [78]:
# considers only the values that satisfy the condition x%3==0
x[x % 3 == 0]

array([-6,  0,  6])

### Numpy arithmatics and statistical operations


In [146]:
# creates an array contains values in between [-3..5[
x = np.arange(-3, 5, 0.5)
print("x:")
print(x)
print()

print("abs: ", np.abs(x), "\n") # returns the absolute values
print("sqrt: ", np.sqrt(abs(x)), "\n") # returns the square root for each item
print("sign: ", np.sign(x), "\n") # returns the sign value for each element
print("exp: ", np.exp(x), "\n")  # returns exponentiation for each element
print("sorted array: ", np.sort(x), "\n") # returns a sorted array

x:
[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5
  4.   4.5]

abs:  [3.  2.5 2.  1.5 1.  0.5 0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

sqrt:  [1.73205081 1.58113883 1.41421356 1.22474487 1.         0.70710678
 0.         0.70710678 1.         1.22474487 1.41421356 1.58113883
 1.73205081 1.87082869 2.         2.12132034] 

sign:  [-1. -1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.] 

exp:  [4.97870684e-02 8.20849986e-02 1.35335283e-01 2.23130160e-01
 3.67879441e-01 6.06530660e-01 1.00000000e+00 1.64872127e+00
 2.71828183e+00 4.48168907e+00 7.38905610e+00 1.21824940e+01
 2.00855369e+01 3.31154520e+01 5.45981500e+01 9.00171313e+01] 

sorted array:  [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5
  4.   4.5] 



### operations on two arrays

In [147]:
x1 = np.array([2, 3])
x1

array([2, 3])

In [148]:
x2 = np.array([3, 2])
x2

array([3, 2])

In [153]:

x1 * x2 # np.multiply(x1, x2)

array([6, 6])

In [152]:
np.dot(x1, x2)

12

#### two-dimentional arrays

In [154]:
x1 = np.arange(1,5).reshape(2, 2)
x1

array([[1, 2],
       [3, 4]])

In [156]:
x2 = np.arange(5, 9).reshape(2, 2)
x2

array([[5, 6],
       [7, 8]])

In [157]:
x1 * x2 # element-wise

array([[ 5, 12],
       [21, 32]])

In [159]:
np.dot(x1, x2) # matrix multiplication

array([[19, 22],
       [43, 50]])

<hr>

### element-wise operations

In [91]:
x = np.arange(-3, 3)
y = np.random.randn(6)
print("x: ", x)
print("y: ", y)

print("x+y: ", np.add(x,y))  # returns an array after applying an element-wise addition
print(np.subtract(x,y))      # returns an array after applying an element-wise subtraction
print(np.multiply(x,y))      # returns an array after applying an element-wise multiplication
print(np.divide(x,y))        # returns an array after applying an element-wise division
print(np.maximum(x,y))       # returns an array after applying an element-wise maximum      

x:  [-3 -2 -1  0  1  2]
y:  [-0.25737728 -1.75016021 -1.5605778  -0.29633394 -0.10188751  0.27691761]
x+y:  [-3.25737728 -3.75016021 -2.5605778  -0.29633394  0.89811249  2.27691761]
[-2.74262272 -0.24983979  0.5605778   0.29633394  1.10188751  1.72308239]
[ 0.77213183  3.50032042  1.5605778  -0.         -0.10188751  0.55383522]
[11.65604063  1.14275253  0.6407883  -0.         -9.81474541  7.22236482]
[-0.25737728 -1.75016021 -1.          0.          1.          2.        ]


<hr>

### statistical operations

In [99]:
y = np.random.randn(2, 5) * 5   # generate a random two dimensional array
print("y=")
print(y)
print()

print("Min =", np.min(y))             # returns the minimum value in an array 
print("Max =", np.max(y))             # returns the maximum value in an array 
print("Average =", np.mean(y))        # returns the mean/average of elements of an array
print("Std deviation =", np.std(y))   # returns the standard deviation of elements of an array
print("Sum =", np.sum(y))             # returns the total summation of the lements of an array 

y=
[[ -2.23354529   1.15668844  -3.92677141   1.13792283   2.94573719]
 [ -1.68514259 -10.5200091    9.47693212   0.49473461   3.30802504]]

Min = -10.520009095191298
Max = 9.47693212115603
Average = 0.015457183319887413
Std deviation = 4.96212015618091
Sum = 0.15457183319887413


### Exercise

1. what is the difference between np.arange and range?

In [42]:
# write your answer
# np.arange returns ndarray instead of list as the case in range

2. two lists <code>\[4, 5, 6, 7, 8]</code> and <code>\[0, 1, 0, 1, 0]</code>. multipy two lists using np.multiply (*)


In [160]:
# write your code here


3. what are the outputs of dot product on the two arrays: 
- <code>\[-1, 1]</code> and <code>\[1, 1]</code> 
- <code>\[1, 0]</code> and <code>\[0, 1]</code>
- <code>\[1, 1]</code> and <code>\[0, 1]</code>

4. why the last dot product output is different than the others?


In [161]:
# 3. write your code here


# 4. justify?


## Prepared by

#### Abdulkarim M. Jamal Kanaan
<a href="">Linked-In</a> 